name:
	rmds-covid-env
channels:
	- base
	- conda-forge
	- anaconda
	- bioconda
dependencies:
	- basemap 
	- geopandas
	- jupyter
	- matplotlib
	- pandas>=1.0
	- scikit-learn=0.23
	- seaborn
	- snakemake